### ISSUE TITLE
support for archaea genomes

### ISSUE THREAD

**Issue by jianshu93** [iimog/bcgTree#53]
Hello @iimog ,

I think archaea has a different set of core genes, which we need to specify alone. In the case of gtotree software they separate those 2 cases. It would be nice if there can be such an option in th GUI interface.

Thanks,

Jianshu

**Comment by iimog** [comment]
`bcgTree` can work with any set of genes given in a hmm file. In order to use a hmm file other than the default, just provide the path to that file under `--hmmfile` in "Advanced settings". This way you can use any of the files listed in https://github.com/AstrobioMike/GToTree/blob/master/hmm_sets/hmm-sources-and-info.tsv (you need to manually download them beforehand).
